apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-session-cleanup
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 11
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: django-app
            image: localhost:5000/django_test:latest
            envFrom:
              - configMapRef:
                  name: django-app-config
            imagePullPolicy: IfNotPresent
            command:
            - ./manage.py
            - clearsessions
          restartPolicy: OnFailure